local ErrorColor = "#ec5241"
local OkColor = "#a3ba5e"
local HintColor = "#99ff99"
local WarnColor = "#efb839"
local InfoColor = "#7ea9a7"

local inactiveColor = "#d3d7cf"

local colors = {
	default = {
		"Normal",
		"WinBar",
		"WinBarNC",
		"NormalNC",
		"NormalFloat",
		"NormalSB",
		"ColorColumn",
		"LineNr",
		"SignColumn",
		"SignColumnSB",
		"Folded",
		"FoldColumn",
		"FloatTitle",
		"FloatBorder",
		"WinSeparator",
		"BufferLineFill",
		"BufferLinePick",
		"BufferLineBufferSelected",
		"BufferLineBufferVisible",
		"BufferLineDevIconDefault",
		"BufferLineIndicatorSelected",
		"BufferLineIndicatorVisible",
		"BufferLineModified",
		"BufferLineModifiedSelected",
		"BufferLineSeparator",
		"BufferLineSeparatorSelected",
		"BufferLineSeparatorVisible",
		"BufferLineTabSeparatorSelected",
		"BufferLineTabSeparator",
		"NeoTreeFloatBorder",
		"NeoTreeFloatTitle",
		"NeoTreeFloatNormal",
		"NeoTreeNormal",
		"NeoTreeNormalNC",
		"NeoTreeGitRenamed",
		"NeoTreeGitStage",
		"NeoTreeGitConflict",
		"NeoTreeGitUnstage",
		"NeoTreeGitUntracked",
		"NeoTreeEndOfBuffer",
		"TelescopeBorder",
		"TelescopePromptBorder",
		"TelescopePromptTitle",
		"TelescopeNormal",
		"TelescopeSelectionCaret",
		"GitSignsAdd",
		"GitSignsRemove",
		"GitSignsDelete",
		"GitSignsChange",
		"GitSignsAddPreview",
		"SagaBorder",
		"SagaTitle",
		"NoiceCmdLinePopupBorder",
		"NoiceCmdLinePopupTitle",
		"NoiceCmdLineIcon",
		"NoiceCmdlineIconSearch",
		"NoiceCmdlinePopupBorderSearch",
		"NoiceCmdlineIconFilter",
		"CybuBackground",
		"CybuBorder",
		"TroubleNormal",
		"TroubleCount",
		"NvimTreeNormal",
		"NvimTreeNormalNC",
	},

	forBuf = {
		"SignColumn",
		"Folded",
		"BufferLineFill",
		"BufferLinePick",
		"BufferLineSeparatorSelected",
		"BufferLineSeparatorVisible",
		"BufferLineSeparator",
		"NeoTreeFloatBorder",
		"NeoTreeFloatTitle",
		"NeoTreeFloatNormal",
		"NeoTreeNormal",
		"NeoTreeGitRenamed",
		"NeoTreeGitStage",
		"NeoTreeGitConflict",
		"NeoTreeGitUnstage",
		"NeoTreeGitUntracked",
		"NeoTreeEndOfBuffer",
		"TelescopeBorder",
		"TelescopeNormal",
		"TelescopeSelectionCaret",
		"SagaBorder",
		"SagaTitle",
	},

	forCmd = {
		"NoiceCmdLinePopupBorder",
		"NoiceCmdLinePopupTitle",
		"NoiceCmdLineIcon",
		"NoiceCmdlineIconSearch",
		"NoiceCmdlinePopupBorderSearch",
		"NoiceCmdlineIconFilter",
	},

	withFgBg = {
		{ "GitSignsAdd", { fg = "#6d9571" } },
		{ "GitSignsDelete", { fg = "#ff0000" } },
		{ "GitSignsChange", { fg = "#eed26e" } },
		{ "GitSigns", { fg = "#ff0000" } },
		{ "Visual", { fg = "#1c1c1c", bg = "#e4e4e4" } },

		{ "BufferLineModified", { fg = "#6d9571" } },
		{ "BufferLineModifiedSelected", { fg = "#6d9571" } },
		{ "BufferLineInfo", { fg = "#2b2c2d" } },
		{ "BufferLineInfoVisible", { fg = inactiveColor } },
		{ "BufferLineInfoSelected", { fg = InfoColor } },
		{ "BufferLineInfoDiagnostic", { fg = "#2b2c2d" } },
		{ "BufferLineInfoDiagnosticVisible", { fg = inactiveColor } },
		{ "BufferLineInfoDiagnosticSelected", { fg = InfoColor } },
		{ "BufferLineError", { fg = "#2b2c2d" } },
		{ "BufferLineErrorVisible", { fg = inactiveColor } },
		{ "BufferLineErrorSelected", { fg = ErrorColor } },
		{ "BufferLineErrorDiagnostic", { fg = "#2b2c2d" } },
		{ "BufferLineErrorDiagnosticVisible", { fg = inactiveColor } },
		{ "BufferLineErrorDiagnosticSelected", { fg = ErrorColor } },
		{ "BufferLineWarning", { fg = "#2b2c2d" } },
		{ "BufferLineWarningVisible", { fg = inactiveColor } },
		{ "BufferLineWarningSelected", { fg = WarnColor } },
		{ "BufferLineWarningDiagnostic", { fg = "#2b2c2d" } },
		{ "BufferLineWarningDiagnosticVisible", { fg = inactiveColor } },
		{ "BufferLineWarningDiagnosticSelected", { fg = WarnColor } },
		{ "BufferLineHint", { fg = "#2b2c2d" } },
		{ "BufferLineHintVisible", { fg = inactiveColor } },
		{ "BufferLineHintSelected", { fg = HintColor } },
		{ "BufferLineHintDiagnostic", { fg = "#2b2c2d" } },
		{ "BufferLineHintDiagnosticVisible", { fg = inactiveColor } },
		{ "BufferLineHintDiagnosticSelected", { fg = HintColor } },

		{ "BufferLineTruncMarker", { fg = "#aaaaaa" } },
		{ "BufferLineBackground", { fg = "#888888" } },
		{ "BufferLineBufferSelected", { fg = "#ffffff" } },
		{ "BufferLineOffsetSeparator", { fg = "#555555" } },
		{ "BufferLineTab", { fg = "#666666" } },
		{ "BufferLineTabSelected", { fg = "#ffffff" } },
		{ "BufferLineNumbers", { fg = "#666666" } },
		{ "BufferLineNumbersVisible", { fg = "#666666" } },
		{ "BufferLineNumbersSelected", { fg = "#ffffff" } },

		{ "DiagnosticSignError", { fg = ErrorColor } },
		{ "DiagnosticSignOk", { fg = OkColor } },
		{ "DiagnosticSignHint", { fg = HintColor } },
		{ "DiagnosticSignWarn", { fg = WarnColor } },
		{ "DiagnosticSignInfo", { fg = InfoColor } },
		{ "DiagnosticVirtualTextError", { fg = ErrorColor } },
		{ "DiagnosticVirtualTextOk", { fg = OkColor } },
		{ "DiagnosticVirtualTextHint", { fg = HintColor } },
		{ "DiagnosticVirtualTextWarn", { fg = WarnColor } },
		{ "DiagnosticVirtualTextInfo", { fg = InfoColor } },
		{ "LineNr", { fg = "#747474" } },
		{ "NotifyERRORBorder", { fg = ErrorColor } },
		{ "NotifyERRORIcon", { fg = ErrorColor } },
		{ "NotifyERRORTitle", { fg = ErrorColor } },
		{ "NotifyERRORBody", { fg = ErrorColor } },
		{ "NotifyWARNBorder", { fg = WarnColor } },
		{ "NotifyWARNIcon", { fg = WarnColor } },
		{ "NotifyWARNTitle", { fg = WarnColor } },
		{ "NotifyWARNBody", { fg = WarnColor } },
		{ "NotifyINFOBorder", { fg = OkColor } },
		{ "NotifyINFOIcon", { fg = OkColor } },
		{ "NotifyINFOTitle", { fg = OkColor } },
		{ "NotifyINFOBody", { fg = OkColor } },
		{ "NotifyTRACEBorder", { fg = OkColor } },
		{ "NotifyTRACEIcon", { fg = OkColor } },
		{ "NotifyTRACETitle", { fg = OkColor } },
		{ "NotifyTRACEBody", { fg = OkColor } },
		{ "NotifyDEBUGBorder", { fg = HintColor } },
		{ "NotifyDEBUGIcon", { fg = HintColor } },
		{ "NotifyDEBUGTitle", { fg = HintColor } },
		{ "NotifyDEBUGBody", { fg = HintColor } },
		{ "LineNr", { fg = "#ffffff" } },
		{ "LineNrBelow", { fg = "#747474" } },
		{ "LineNrAbove", { fg = "#747474" } },
		{ "EndOfBuffer", { fg = "#111111" } },
		{ "WinSeparator", { fg = "#555555" } },
		{ "NeoTreeWinSeparator", { fg = "#555555" } },
		{ "NeoTreeTabInactive", { fg = "#666666" } },

		{ "NeoTreeTabSeparatorActive", { fg = "#555555" } },
		{ "NeoTreeTabSeparatorInactive", { fg = "#555555" } },
		{ "TelescopeSelection", { fg = "#fff000" } },
		{ "TelescopeResultNormal", { fg = "#ffffff" } },
		{ "TelescopeResultTitle", { fg = "#ffffff" } },
		{ "TelescopeResultBorder", { fg = "#ffffff" } },
		{ "TelescopePromptNormal", { fg = "#ffffff" } },
		{ "CybuFocus", { bg = "#e4e4e4", fg = "#1c1c1c" } },
		{ "NvimTreeEndOfBuffer", { fg = "#111111" } },

		{ "TabLine", { bg = "#111111" } },
		{ "TabLineFill", { bg = "#111111" } },
		{ "StatusLine", { bg = "#111111", fg = "#999999" } },

		{ "BufferLineDevIconLua", { fg = "#666666" } },
		{ "BufferLineDevIconLuaInactive", { fg = inactiveColor } },
		{ "BufferLineDevIconJsx", { fg = "#666666" } },
		{ "BufferLineDevIconJsxInactive", { fg = inactiveColor } },
		{ "BufferLineDevIconJs", { fg = "#666666" } },
		{ "BufferLineDevIconJsInactive", { fg = inactiveColor } },
		{ "BufferLineDevIconTestJs", { fg = "#666666" } },
		{ "BufferLineDevIconTestJsInactive", { fg = inactiveColor } },
		{ "BufferLineDevIconDefault", { fg = "#666666" } },
		{ "BufferLineDevIconDefaultInactive", { fg = inactiveColor } },
		{ "BufferLineDevIconGitIgnore", { fg = "#666666" } },
		{ "BufferLineDevIconGitIgnoreInactive", { fg = inactiveColor } },
		{ "BufferLineDevIconTxt", { fg = "#666666" } },
		{ "BufferLineDevIconTxtInactive", { fg = inactiveColor } },
		{ "BufferLineDevIconMd", { fg = "#666666" } },
		{ "BufferLineDevIconMdInactive", { fg = inactiveColor } },
		{ "BufferLineDevIconCss", { fg = "#666666" } },
		{ "BufferLineDevIconCssInactive", { fg = inactiveColor } },
		{ "BufferLineDevIconEditorConfig", { fg = "#666666" } },
		{ "BufferLineDevIconEditorConfigInactive", { fg = inactiveColor } },
		{ "BufferLineDevIconCjs", { fg = "#666666" } },
		{ "BufferLineDevIconCjsInactive", { fg = inactiveColor } },
		{ "BufferLineDevIconHtml", { fg = "#666666" } },
		{ "BufferLineDevIconHtmlInactive", { fg = inactiveColor } },
		{ "BufferLineDevIconPackageJson", { fg = "#666666" } },
		{ "BufferLineDevIconPackageJsonInactive", { fg = inactiveColor } },
		{ "BufferLineDevIconJson", { fg = "#666666" } },
		{ "BufferLineDevIconJsonInactive", { fg = inactiveColor } },
		{ "BufferLineDevIconSvg", { fg = "#666666" } },
		{ "BufferLineDevIconSvgInactive", { fg = inactiveColor } },

		{ "NvimTreeWinSeparator", { fg = "#555555" } },
	},
}

return colors
